### ISSUE TITLE
Parse error: source must be an array. See console logs for more info.

### ISSUE THREAD

**Issue by yumyo** [tokens-studio/style-dictionary-configurator#39]
HI, we have a "global" Tokens set and two other sets: "Dark-Thme" and "Light-Theme".

We select "Multiple Files" when exporting from the Tokens Studio plugin (pro license). 
However, when trying to import in the configurator, we get a: 
"Parse error: source must be an array. See console logs for more info." error.

The log shows just the same, with several:
```
dex.js:41470 Error: source must be an array
    at Object.extend (index.js:36439:13)
    at index.js:41460:34
    at new Promise (<anonymous>)
    at index.js:41457:11
    at Array.map (<anonymous>)
    at SdState._runStyleDictionary (index.js:41455:12)
    at SdState._prepareRunStyleDictionary (index.js:41438:14)
    at async SdState.runStyleDictionary (index.js:41413:7)
    at async saveFile (index.js:42024:5)
(anonymous) @ index.js:41470
4index.js:18644 Uncaught (in promise) TypeError: path must be a string or Buffer
    at pathToFilename (index.js:18644:19)
    at Volume.writeFileBase (index.js:19434:32)
    at index.js:19044:33
index.js:41418 
```

Also thene.json looks empty, while all other files have data.

**Comment by jorenbroekema** [comment]
From our slack conversation:

[The project where the error is found](https://configurator.tokens.studio/#project=7V39bts4En8VwbsL7O7Frj79sf81TdsUm1zSdQ5doCkOtEQ7amTJoKRsckGAe5x7rnuSJSnZlmSZlijbshU2QONI4vxmyN8MhyNKfm79OIUBsEAAOt99z2391nq+dSXpthV499AdwuAKWRDdtn6TvpLj5MzE8UbAuW2dzA9c2JO7oH1zB6cwcfQMoPv5QXLs26370jpp/RiQQ/4c7es3fMz03LE9ySjgeyEyIUG+bf366xuqT9QsBrltzRwQjD009clVz3Ng00/+TW1BwPXJhR+RF84ikZG8th+Elu0t1KZSERzbj9FVvpU6NQptx7oGwV10lv75BuO9SV01th3oJ7qM/HtefiSXWNAPbBcENrGGiPr3A0A2GOGG7Z9oD/3UoXacpNsRI0AQNSG4i1ZRH0f/XuYfv0UfXhZj8r1az+Sa/30L1q8a/51t+3fwAHwT2bPgDfS7TOPJr5eIe0tKZrg2hFPgBraZ4tE7z/FQpr+GIRoDE0rXyJ4C9JQ6K1FDnDDm7DNt3zkFPuzEl3dOHWDev6Qsw/39NIubmBHi/OTLySrwEGJnsUpALxp0PiL4JBmyXAn/BqLA5ofXK8J/DkEAkcuvgFpRgTPbJ0S1OOG1ivBvHdz/BbCH4Wzm4ZFyJ51hAILQ7xDud2jzSgq8RyjjFKUUoM2rOUBomjAT4UupEAvgUuIGPga8vv/lzg4gP2pVx1c4mUfBK3q9WgW7Jo+j2LW5G0WvzdciwtXpaKceSTv372oxbkXO8c5yMXptrIvxa+NdjF8r8z7hkdw/7yhqTayj2LVxjqLXxjiKvn++ZddlVzNg2sFTZrFBZEtXDxA5gE1FL2reiX+3NQYRvDlUbuDHazcuRIMTkJYOpA+240jn3gNEpUC7vGbSjuUENXhBo+C2T6xiASULqhpVevUdwIUEHzrSKV7pTvBntxz6oBR67EfkV7zEj4pTmeV9diWPOwjHz4y3rYv5dM2eOZqx4gfFUjW1t1KxWBsAkh1HLqQTxwaMMf1XCiN3HbV2HTGvD2zQQ9f1nj7gt3U+V22A6RnkpyKMthFmBEZjU68Io26EGctjdVzVGmUzTI/88HEkOye9fwyga2WCB1mHj6RTXDW0VudL4lTOBg1lGcjmmL8jLm0wtTdimEp/xI9x7rkT6Xf83wYcKMuybvHjvLMDG/qbhhToXaXLD3KNS6v+PzbFL0h+thFbAg+tEgNPtdONzLVMOKhkpolvGJxI1+HISRVy89BMyxqPVX60f7mOPcUh2zr5/3//J713MbSL65L+iXQJkW3ZuKi+QQOML5sVOIqndpPkLphAJxLJRXFR2w3wZ6zQtefbpLa+UQfV0qBZISgBx6EabOxt8sOP8wHiVBvBE+mf3gPYZFMfQlihX99b9vy2BHsu7o0qRLHfwch2YRBsgjGtMQD8MJ9cn+TXhCEheoBPm+EMq1eFk8DxJuFGPlA6mNuZpZYrssw8dYXnqAlk5Z4/jJWBRabU8svGSLjUlkiljIkxGvcNZcCD8Qc7b8cclGVtxCm5iOrmQFbUMQ8Azlagy5QtK4OxoXHLLqK+rPS7XYXrVgNd2q8Ip2vVHGrnFS8K9eYGldJqxarllioKGc+BllcUWsUafOieZdyoCNbaKIKXkTm9XEyXsQ606r1cbETH40FvYO1rRHumqQ/UKr2cjaHkV6QN1uIOWN5f6X0UV2FAirH0TCa4ysp61/uaxF8xyZwvxRerZgUwjbKQN5vrsHJZvEsjj3xP0ak8Hxg5YayCnnPWnyEIrIXg9WNXu23yVm1b/vFtTcgceY9zbfPCpqweCyl0Zsf1j5oUaiVSKFsnhXYspOgzO25lCX5crKjGeHUrrMiZdsaeG3zABR0nvYi8bQEUtEeknNS+w1o4eLGUmYESU+NbFEi09CSdL65NMHCpVBrtNrOSsB8Aalu2P8ve+0iBfcJXkbp6dBUHzNKyIJvBrrEqynSLQyU7mPTGOaSLwFT/yuuBNWMNWEpW1iyFIVDmEaiuF6j2eQRqDIEaj0CdIVDhEWisF6hzmdxlCFR5BPYYo6zzCOyvF2hwCRwwBHLxUGG5ClcnKgxfUbmMVljOwmc1w1u6fDoy3EXncheF5S9dLokMh1G4PFBheIzKxx6Gyyh8VjN8RisjMTuzf8mZeFYn9jbDwU49x2JMfV/WmZScy9sMd/sDTkIHoMoQDP8bwqnNa0Y6V2hrOzEkA6JvbTSydBja/4FFkxBFZQARQeVSEEUvL07l8DOGOI0jtDDE6RwRnyHO4JiSGOIYcVTl6LseR3LJENfnmNEZ4gYcSRGLxjJHOGbJY6XmHMxjJRs6x2iwUg2dJwzoHGn0qrxk9HLwrTqIhmT7Ueo+EzOErc270sJKRDH5Jz6RjAGTOwanUI0lVOOTyRo5PomMuKaUkpikwwwgMEFgdrclRqzKK0EKvazQpCU3TzOPXvSUsoHUUXATX/rZ9KZTz/0lA3+u4Btwfw7bw8vUiZRmmds3i0pFXJB6TpYuOqtZ4cvK7eFlipGQEOccnby0clXEMmmNRSSy2I6cDznPWmJA8menlyM6GyKI9OSxPPl5RMLtsoeZTT+5FnSDbMvoaF5DkuS9i3c/4hbzPzuul9fp5PQZND2UeFjzOX1w3nLZ8GVNUTBIsG1+RbJWfK42kFZKcVp1Ba12QiutgbRSi9PKELTaCa30BtJKK04rXdBqJ7QyGkgrvTitNEGrndCKpuwXDeKUUZxTiiDVDhP2JpGqW4JUsiDV7tL1JpGqJyoLB5GrN4lTYv13GIl6kzglsvRaOBV9SDx4a9mBh2zgSJ9DL/NY+G2LHsPMU7dGveROhpKkS++zKEm3/q4TeIWfb8rriGFzMh09lwYluKTwcEkVXCrIpYuPR86lMoUFec9x6ZXkVnMuXZ4dOZdK1BMGgko7neK2WFI/Ajb1BZv2kKDvfaPMtpin7o55vT0z75WkV1vfHFMXlXa9IUZQae8bYmqjUok9e4bg0lHsgqmNSyXiki64dBRbX2rjUom7M6KyeQT7XWojUon9eMq+N+S9qsT72JkkbrY0bGNLXUQ65Or4q8q5j51IoqTUrB0sogjwuogUfVhWxa/nJuBquBfcQZQthl8r27yjl35tRUnCZV+sUZJyPRG6ag5d12pTuKSK6FU3l5Rt7loRcenVx6VGcEnEpYPIqpY7DHJzqvMd5VQ1vi+hxC50UWDYYcmzUaySxcx4CNXPZkWq4pwSG1l2VwhtFKdE1nUQRdFGcWrXj/UJThXajLCDVWGNc1+Z24CqYNXOsvRGsWrnb98QpCqUpjeKVGLpdxBpeqM4JdL0g0jTG8UpkaYfRMH9wnbv/UyV/QYDSuQEWRpCyw6n0s9ncAxCJ/hl6wysfqtHL5vMlwhnXLm8ePHLpnCWx7Bz8v3ugl+vmV8hxkLxdFSdZO8fcZ+5wBGhrLFUC2cziEz8qeZ4dhoGgecuONYEZpUpTghm7TZJG2JtPBTYqe9eodkbGEGH7moGaAKbQLuemDtrjmVzTjWGUq88kh0QpZozO5Z4vlC8N3unnBpOgeMcIKW0Q6OUJihVJNc69aynvHrY4U6IpZlWYieXePHx7upfBzwflqaUSNsPhFKNmQ5F1n5gD2SM7UdoZR/IkJWtc625tyR1UfIqEslktUGc2nkcMwSpCgez68Qz+/lvsL3e3Vc9N++ZRjGFFno+til0El+WehCP7u/gO5j2zyXxHXGHEZqawCUxzR3s1wTs4SF+8WJA8dy+eDGg4FEVHmlN4JFS4kvhxAP6R/CAvnjDpHgqX3zHhCBSJSJt9VF88TZ38fS9WLQJIlUiktYEIolFW7OesheLNvFovVi0CSKVJlL0gf6K2t22/GVvxNS5bamZGviCXPjU7DGhdxJwISgGWZTa9fXS9PLS+uul9ctLUximKhy2Kl2GvG55earMGAqZQx5jMFSO0dAY/afxcIVhr85hr86gi87BF4MxvgbH+HYZ49HlGI8eYzx6HOPRZ4xHn2M8Boz+G3D0n8J0YC4PZrmcUsLnkkE2OQ8soiwJ5euhorO5SEtpWeUX+9fWy01cUkx41o70DLUda5IyV2yav2aBYdPykjIQSctypviFaQxCrKeDZU+h66+D8whZgqcUTHysrbDwOsoavIXEbP/NxbKk8so0WJrKBq9YlSlX5ZarMXtW4xWrM8Xq3J3LFMvdCV2m2C6v2B5TbI9XbJ8pts8rdsAUO+AWyyTugHvMFJk1KRWUmow/U/DY/su2grtUBPKnjGxJ0YrEusR5C/omsmfLtcwleJS+EFBp7CEpuIPS8JI+VQakzyFET9IIQXA/82wSf7NdMbUYmU23v33dLs8K6+ZMGKMjM/JqbuUuPhZW7tFh5TN9efvK/XlRWDmVqZ2hdbevnbpZPeopt+5L66R1QQoW7Zs7OIWd777ntn5rPUcuNIRT4Aa2mfKgd57joYxFwxCNgQmla2RPAUo/rpux+Jm275ySGkF8eefLnR1kigXJfjAjxPnJZK1oDjzEqY9rlYBeNOh8RPBJwtGnEv4NRIHND69WhP8cAvpqLW4F9IoKnNk+GDnQ4oTXKsK/dXD/F8BevrenMwxAEPodSv4ObV9Jg/cIZbyinAa0fTUXCE0T+n4FHWIJXFrckKddOd3/1AHmPT9qVd83OMlHwSs6vl4Fuyano9j1eRyFr8/dIsrV6munHsLFgP17W4xbkXa8lI/R6yNerEB91IsVqJd8n/Bg7p96FLUm4lHs+mhH4esjHYWvgXLZZdTVSjmRHD0D6F66esClUcBmY1wp6CzrZOtVyVQVMvHfdiAXosEJSPtP+mA7jkTfyFwKtMtrJu1YTlCDFzQKcPvEKhZTsqCqUaVX3wHkhT50pFMcDSf4s1sOfVAKPfYj8ouu91/+Bg==)

This is missing content in the $themes.json, as well as source not being `%themeTokenSets%` (special thing for the configurator to understand what to do).

[Fixed project here](https://configurator.tokens.studio/#project=7V0Pc5s4Fv8qjG932s7ZDmD8L3t7c5umbTrbXtN17roz686tDHJMi8EjRDe5TGbu49znuk9ykgAbsC2DsIND1Mw0DqD3e3r6vaenh8B3je/mEAMLYND+4ntu47RxN3YVZdzA3lfojiD+gCyIxo1T5Td6nJ65drwJcMaNZnzgnX09w62rGZzDxNFzgL7GB+mxz2P3vtFsfIfpIT9G+22MwgZ38YewtQtou9NQDJWaOutDB5oYWleRkj5VMCUhreopbeMFyIQZUeuq0kuhCyYOtIjeiUvv4z/um8oupZlFDq11yuw51KYfPpMRMD13al9nhjvGoXK+Z0O01PL7aFDHjYUD8NRD80jxaKBNP/k34w4Crk8vfIO8YBEKZXzyWz4OLNtb0oRJRXBq30TdtVKnJoHtWJcAz8Kz7M8TgneSumpqO9BPUDQcGTdpKwv62HYBtj03FPWvbwDZ1Fx+K+zu923Wj2a6He0EwGETirtsFXI6NnH08XNMkNg0X8pZZmP3v+yh9+ud/8Lv+xfwDfgmshf4BPo9bufpr/vQ11d+lWHbCM6Bi20zxaOXnuOhjL1GAZoCEyqXyJ4DdJs6q7COOEHE2jvWvn0GfNiOLm+fOcD8ep/qGbH37SJqYoaI8cn75jrwCBJ3sQpALxu03yB4q3RVtRT+FUTYFoc3SsJ/DACGyBVXQC+pwLntR0FNCL5TEv4nh9g/B/YoWCw8MlLudXuEAQ78NuV+mzUvpcArhDJOUUgB1rycAwSmCTMRvpAKkQAhJa7gDRb1/U8zG0Nx1LKOrwkyj4GX9Hq9DHZFHsewK3M3hl6Zr4WEq9LRzjya5j+8q0W4JTknOstF6JWxLsKvjHcRfqXMe0tG8uF5x1ArYh3DroxzDL0yxjH0h+dbdl32YQFMG99mFhtUtvLhG0QO4FPRC5u3o9+tDocIXgy1MfCTtZsQYlcQkNUMlNe24ygX3jeICoH2RLvJDCsI2hUFDYPbQ2LlCyhZUL1bxqovASkkkMKSckZWutfks1sMfVgIPfIj+ita4oe1qszyPruSJwYi8TPjbdtiPluzZ45mevEnzdI7en+tYrE1ACQNRy9kE8cOjCn7Vwhj4zpq6zoirg/s0MMwjL4xFO9rPFftgOl36U9JmM5OmAmYTE2jJIy+E2aqTvVp2d5ou2H69EeMI9k56dUNhq6VCR50HT5RzkjV0FqfL6lTOTs0VFWgmlNxQ7y3wdzeiWFqg4k4xoXnXis/k/924EBVVQ1LHOeljW3o7xpSYPS0njjIJSmt+n/eFb8g/dlHbMEeWicGmWrnO5lrmXBYqpsmuWXQVC6DiZMq5G5CMy1rOtXF0f7hOvachGyr+b///Fd55RJol9Ql/abyHiLbsklRfYcGBF81S3CUTO0mzV0IgZoKzUVJUdvF5DNR6NLzbVpb36mDbnWgWSIoAcdhGuy0Nv0Rx3kNSaqNYFP5u/cN7OrTAEJYwq6vLDu+LcGfi/uTElHsZzCxXYjxLhjTmgIgDvPW9Wl+TRkSoG/wdjdc1+qX4SRwvOtgJx8YHcz9zFKrFVlmnvpA5qhryMs9/zTVhhadUosvG0PhSkuhlTIuxmQ66GpDEYxf+Hk74aCqdiaCkvOobg5VTZ+KAJBsBbpc2ao2nHY7wrLzqK9qg15PE7rVwJb2a8Kjm+hr1N5UvMhlzR0qpdWKVNtYqsjVeQG0TUWhdazh6955xo3yYG2NImyDxZqV8+kyNUCnvJXzjeh0OuwPrYca0b5pGkO9jJWzMZT+CrUhWsyA5f2R3kfxIcC0GMvOZIKrqm13vd+S+GtdMuOl+HLVrAFupyzkLWId1i6LdmlsIt9teGqTD0ycIFLB2HDWXyAIrKXg7WNXed/UvfZt9cfnLSFz4t3E2m4Km6r+WEhhcA03eNSk0EuRQts7KTqPhRQDruHWluCPixXlGK/vhRUbpp2p5+LXpKDjpBeR4wZAuDWh5aTWjGjhkMVSZgZKTI0/Iayw0pNysbw2wcCVUmm0cWYlYX8DqGXZ/iJ77yMF9pZcRevq4VUCMKue4WwGu6VXYaabHyppYGqNC8gWgSn7qtuBO90tYClZ2W5pHIGqiEB9u0B9ICKwwxHYERFocARqIgK72wUaQl3ucQTqIgL7nFE2RAQOtgvsCgkccgQK8VDjuYqQETWOr+hCndZ4ziLWa4639MR05LiLIeQuGs9fekISOQ6jCXmgxvEYXYw9HJfRxHrN8ZlOEYnZmf3TholnfWJvcRzszHMsztT3aVuXknN5i+Nuv8DrwAGoNATH/0Zwbot2I50rtDoH6UgGxNjbaGTpMLL/DfMmIZrOAaKCiqUgmlFcnC7gZxxxHYHQwhFnCER8jriuwJTEEceJo7qA7foCySVH3EBgRueIGwokRTwaqwLhmCePl5oLMI+XbBgCo8FLNQyRMGAIpNHr8pLRyyG36iAa0e1HqftM3BC2Ne9KCysQxdTvxURyBkxtdwWFdnhCO2IyeSMnJpET17RCEpN0WAAErhFYzPbEiHV5BUhhFBWa7MnV7cJjF92m+kDrKKSJrzw3vfncc19k4C80cgPu11Fr9D51IqVZ5vbNslIRFaTukqWL9npWeL92e3iVYiQkRDlHe1NauS5ilbRGIhJZbFvdDBlnLREg/bPd3yA6GyKo9OSxTfI3EYm0yx7mNn3rWtDF2Zbh0U0NaZL3Mtr9SFrEf7Zdb5PR6elzaHoo8bDmXfpg3HLV8H5LURAn2BZfkawVX+g1pJWWn1Y9SauD0KpTQ1rp+WnVlbQ6CK2MGtKqk59WhqTVQWjVrSGtjPy06khaHYRWLGV/VyNOdfNzSpOkOmDCXidS9QqQSpWkOly6XidS9WVl4Shy9TpxSq7/jiNRrxOnZJZeCafCD4kHby0be8gGjvIx8DKPhY8b7Bhhnr436iV3MhQkXXqfRUG6DQ6dwGvifNOeRgyLyfTouTQswCVNhEu65FJOLr1788i5VKSwoD5wXHoiuVXMpffnj5xLBeoJQ0mlg05xeyypPwI2DSSbHiBBf/CNMvtinn445vUfmHlPJL3a++aYqqh06A0xkkoPviGmMioV2LPXlVx6FLtgKuNSgbhkSC49iq0vlXGpwN0ZWdl8BPtdKiNSgf142kNvyHtSifdjZ5K82VKzjS1VEemYq+NPKud+7ESSJaV67WCRRYCnRaTww6oqfhl3gVTDPTyDKFsMv9T2eUcv/dqKgoTLvlijIOX6MnRVHLou9bpwSZfRq2ouafvctSLj0pOPS7XgkoxLR5FVrXYYbMypLg6UU1X4voQCu9BlgeGAJc9asUqVM+MxVD/rFanyc0puZDlcIbRWnJJZ11EURWvFqUM/1ic5lWszwgFWhRXOfUVuA+qSVQfL0mvFqoO/fUOSKleaXitSyaXfUaTpteKUTNOPIk2vFadkmn4UBfd3tvvVz1TZrwigQk/QpSG07GCuPD+HUxA4+MXeGVj+Vo9RNJkvEM6Ecnn54pdd4WwTwy7o97tLfj1lfgUEC0XTUXmSvbohNnOBI0NZbakWLBYQmeRTxfHsLMDYc5ccqwOzihQnJLMOm6SNiDYewnbqu1dY9gYm0GG7mgG6hnWgXV/OnRXHsphTtaHUE49kR0Sp+syOBZ4vlO/NPiinRnPgOEdIqc6xUaojKZUn1zrzrNtN9bDjnRALM63ATi754uPD1b+OeD4sTCmZth8JpWozHcqs/cgeyJjaN9DKPpChanvnWn1vSRqy5JUnkql6jTh18DjWlaTKHcwuE8/sb36D7eXhvuq5fs80yik01/OxdaGT/LLUo3h0/wDfwfTwXJLfEXccoakOXJLT3NF+TcADPMQvXwwon9uXLwaUPCrDo04deKQV+FI4+YD+I3hAX75hUj6VL79jQhKpFJH2+ii+fJu7fPpeLtokkUoRqVMHIslFW72espeLNvlovVy0SSIVJlL4gf0K240b/soaEXXGDT1TA1+Si5xa3CT0TgIuBUUgy1K7sV2aUVzaYLu0QXFpGqermkBftR5HXq+4PF3lDIUqII8zGLrAaHQ49uuIcIXTX0OgvwaHLoYAX7qc8e0KjG+PMx49gfHoc8ajLzAeA854DATGY8ix31DAfhrXgYU8mOdyWgGfSwbZ5DywjLI0lG+HCs9uRFpJyyq/3L+2XW7iknzCs/1Iz1D76U1S5lqf4tcscPq0uqQIRLJnG6b4Zdc4hNhOB8ueQ9ffBudRsuDbFEx0rKXx8NraFrylxKz9YrE8qaIyuzxN1a6oWJ0rVxeW2+FatiMq1uCKNYSNyxUrbIQeV2xPVGyfK7YvKnbAFTsQFTvkih0Ki+USdyg8ZprKm5RySk3Gnzm4af1hW3iWikD+nJMtaZ08sS5x3oK+iezFai3zHtwonyioMvWQgmdQGb1nT5UB5WMA0a0yQRB8XXg2jb9ZU8wtTmbTG+xft/fnuXVzrjmjo3LyamHl3r3JrdyNw8tnBur+lfv1XW7ldK523U5v/9rpu9VjnjJ27xvNxjtasGhdzeActr/4nts4bdyFLjSCc+Bi20x50EvP8VCmR6MATYEJlUtkzwFKP66b6fEda98+ozWC6PL2p5mNM8WCpB3MEDE+mawVxcAjkvq4VgHoZYP2GwRvFRJ9SuFfQYRtcXi9JPzHALBXawkrYJRU4Nz2wcSBliB8pyT8Tw6xfw7s1Xt72iMMcOC3GfnbrH0pDV4hlPGKYhqw9uVcIDBN6PsldIgkCGlxRZ92FXT/MweYX8VRy/p+V5B8DLyk4xtlsCtyOoZdnccx+OrcLaRcpb525iFSDHh4b4twS9JOlPIRenXEixSojnqRAtWS7y0ZzIenHkOtiHgMuzraMfjqSMfgK6Bcdhn1Ya2cSI+eA/RV+fCNlEYBn41RpaC9qpNtVyVTVcjEf9uBQohdQUBmP+W17TgKeyNzIdCeaDeZYQVBu6KgYYB7SKx8MSULqnfLWPUlQF7gQ0c5I9Hwmnx2i6EPC6FHfkR/Ret9BK9tn24kOH8duCatI/hk3U9W/facuq4ywrcOPLfZGRI8lSny5soznx5tWcvDz34Yu1GDOyUWeYWA65MqxNxX7qN2f8PeV1LFaPk4sGzvxLdaeHkRlTF2T06U1NGmoruWQu9WzCGRyaoaHqt3+IoJXGUCFWBZZMhoyxGEiuWZ/qkyw3jhn56cXNt4Fkzapjc/4UCP3XWdn2d6/iJWD96A+YK4PRsVZSmkqfwxs82Z8iXwMTEBDhDRkNZfGK4CfMUmOBmh7TXc52zk6Rierkaeja9LLECPzW9fEghvvmwSnZ8DbM4gOlWeM8QXyo9/Ve5Cvi2VzJ4O+RBqGyr6g0K6+JdWa9WGqu5CyGwc0uZFZAl6FmBlBh1yi80PhzjLjLFLpgyf0mJKYiV99hCiZtQSQ+ufANnU5ShFfsySrR1edhHKz9rf9P1IznazvmbnQ5uG9nsWmy889YzZJ1aHWGcaecHzu1Ufmkz3Zsy7+xex4eKueQFeBPgXOIUIumbUmejqH1I2/v27u5UdnrPP9y/uT5HnYSqUnF2zzPPoGNGddPlZU0kqlkUmwsgA/f7DcqjIp8b9/wE=)

[See also, how to set up themes in figma plugin](https://docs.tokens.studio/themes/themes-pro)
